import { Geist, Geist_Mono, Josefin_Sans } from "next/font/google";
import "./globals.css";

type CustomMetadata = {
  title: {
    template: string;
    default: string;
  };
  description: string;
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const josefin = Josefin_Sans({
  subsets: ["latin"],
  display: "swap",
});

export const metadata: CustomMetadata = {
  title: {
    template: "%s / Fourthview-Trading",
    default: "Welcome / Fourthview-Trading",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${josefin.className} ${geistSans.variable} antialiased flex flex-col min-h-screen`}
      >
        {children}
      </body>
    </html>
  );
}
