import { Outfit } from "next/font/google";
import { Bounce, ToastContainer } from "react-toastify";
import "./globals.css";
import { Providers } from "./providers";

type CustomMetadata = {
  title: {
    template: string;
    default: string;
  };
  description: string;
};

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
  display: "swap",
});

export const metadata: CustomMetadata = {
  title: {
    template: "%s / Fourthview-Trading",
    default: "Welcome / Fourthview-Trading",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.className} antialiased flex flex-col min-h-screen`}
      >
        <Providers>{children}</Providers>

        <ToastContainer
          position="top-center"
          theme="dark"
          rtl={false}
          draggable
          pauseOnHover
          pauseOnFocusLoss
          transition={Bounce}
          hideProgressBar
          autoClose={5000}
          closeButton={false}
          className="flex items-center min-w-40 text-sm text-slate-500 rounded-2xl toast-container"
        />
      </body>
    </html>
  );
}
